BLUE_GREEN = [
    '1 - azul,tucuruvi',
    '1 - azul,jabaquara',
    '2 - verde,vila madalena',
    '2 - verde,vila prudente'
]

COMPLETE_MANUAL1 = [
    '7 - rubi,jundiaí',
    '8 - diamante,júlio prestes',
    # '8 - diamante,pres. altino',
    '8 - diamante,amador bueno',
    '8 - diamante,osasco',
    '9 - esmeralda,mendes - vila natal',
    '5 - lilás,capão redondo',
    '1 - azul,jabaquara',
    '1 - azul,sé',
    '3 - vermelha,mal. deodoro',
    # '3 - vermelha,república',
    '4 - amarela,vila sônia',
    # '4 - amarela,paulista',
    '2 - verde,vila madalena',
    '2 - verde,tamanduateí',
    '15 - prata,jardim colonial',
    '10 - turquesa,rio grande da serra',
    '3 - vermelha,brás',
    '3 - vermelha,tatuapé',
    '3 - vermelha,vila matilde',
    '3 - vermelha,corinthians - itaquera',
    '11 - coral,estudantes',
    '12 - safira,calmon viana',
    '13 - jade,aeroporto - guarulhos',
    '3 - vermelha,brás',
    '3 - vermelha,sé',
    '1 - azul,tucuruvi',
]

COMPLETE_MANUAL2 = [
    '7 - rubi,jundiaí',
    '8 - diamante,júlio prestes',
    '8 - diamante,amador bueno',
    '8 - diamante,osasco',
    '9 - esmeralda,mendes - vila natal',
    '5 - lilás,capão redondo',
    '1 - azul,jabaquara',
    '2 - verde,ana rosa',
    '2 - verde,tamanduateí',
    '15 - prata,jardim colonial',
    '10 - turquesa,rio grande da serra',
    '3 - vermelha,brás',
    '3 - vermelha,tatuapé',
    '3 - vermelha,vila matilde',
    '3 - vermelha,corinthians - itaquera',
    '11 - coral,estudantes',
    '12 - safira,calmon viana',
    '13 - jade,aeroporto - guarulhos',
    '12 - safira,brás',
    '1 - azul,sé',
    '1 - azul,paraíso',
    '2 - verde,vila madalena',
    '4 - amarela,vila sônia',
    '3 - vermelha,mal. deodoro',
    '3 - vermelha,sé',
    '1 - azul,tucuruvi',
]

BF_PINH = [
    '7 - rubi,palmeiras - barra funda',
    '8 - diamante,amador bueno',
    '9 - esmeralda,pinheiros',
]

BF_REP = [
    '7 - rubi,palmeiras - barra funda',
    '3 - vermelha,república',
]

BF_LUZ = [
    '7 - rubi,palmeiras - barra funda',
    '1 - azul,luz',
]

PINH_CONS = [
    '9 - esmeralda,pinheiros',
    '2 - verde,consolação',
]

PINH_PARAISO = [
    '9 - esmeralda,pinheiros',
    '9 - esmeralda,mendes - vila natal',
    '5 - lilás,capão redondo',
    '1 - azul,jabaquara',
    '1 - azul,paraíso',
]

REP_CONS = [
    '3 - vermelha,república',
    '2 - verde,consolação',
]

REP_LUZ = [
    '3 - vermelha,república',
    '1 - azul,luz',
]

REP_SE = [
    '3 - vermelha,república',
    '3 - vermelha,sé',
]

LUZ_SE = [
    '1 - azul,luz',
    '3 - vermelha,sé',
]

LUZ_BRAS = [
    '1 - azul,luz',
    '3 - vermelha,brás',
]

SE_PARAISO = [
    '3 - vermelha,sé',
    '1 - azul,paraíso',
]

SE_BRAS = [
    '3 - vermelha,sé',
    '3 - vermelha,brás',
]

PARAISO_BRAS = []

# '1 - azul,ana rosa',
# '1 - azul,jabaquara',
# '1 - azul,japão - liberdade',
# '1 - azul,luz',
# '1 - azul,paraíso',
# '1 - azul,santa cruz',
# '1 - azul,são bento',
# '1 - azul,são joaquim',
# '1 - azul,sé',
# '1 - azul,tucuruvi',
# '1 - azul,vergueiro',
# '1 - azul,vila mariana',
# '10 - turquesa,brás',
# '10 - turquesa,ipiranga',
# '10 - turquesa,juventus - mooca',
# '10 - turquesa,luz',
# '10 - turquesa,rio grande da serra',
# '10 - turquesa,tamanduateí',
# '11 - coral,antonio gianetti neto',
# '11 - coral,calmon viana',
# '11 - coral,corinthians - itaquera',
# '11 - coral,dom bosco',
# '11 - coral,estudantes',
# '11 - coral,ferraz de vasconcelos',
# '11 - coral,guaianases',
# '11 - coral,josé bonifácio',
# '11 - coral,poá',
# '12 - safira,aracaré',
# '12 - safira,brás',
# '12 - safira,calmon viana',
# '12 - safira,comendador ermelino',
# '12 - safira,eng. goulart',
# '12 - safira,eng. manoel feio',
# '12 - safira,itaim paulista',
# '12 - safira,itaquaquecetuba',
# '12 - safira,jardim helena - vila mara',
# '12 - safira,jardim romano',
# '12 - safira,são miguel paulista',
# '12 - safira,tatuapé',
# '12 - safira,usp leste',
# '13 - jade,aeroporto - guarulhos',
# '13 - jade,eng. goulart',
# '15 - prata,jardim colonial',
# '15 - prata,vila prudente',
# '2 - verde,alto do ipiranga',
# '2 - verde,ana rosa',
# '2 - verde,brigadeiro',
# '2 - verde,chácara klabin',
# '2 - verde,consolação',
# '2 - verde,paraíso',
# '2 - verde,sacomã',
# '2 - verde,santos - imigrantes',
# '2 - verde,tamanduateí',
# '2 - verde,trianon - masp',
# '2 - verde,vila madalena',
# '2 - verde,vila prudente',
# '3 - vermelha,anhangabaú',
# '3 - vermelha,artur alvim',
# '3 - vermelha,belém',
# '3 - vermelha,bresser - mooca',
# '3 - vermelha,brás',
# '3 - vermelha,carrão',
# '3 - vermelha,corinthians - itaquera',
# '3 - vermelha,guilhermina esperança',
# '3 - vermelha,mal. deodoro',
# '3 - vermelha,palmeiras - barra funda',
# '3 - vermelha,patriarca - vila ré',
# '3 - vermelha,pedro II',
# '3 - vermelha,penha',
# '3 - vermelha,república',
# '3 - vermelha,santa cecília',
# '3 - vermelha,sé',
# '3 - vermelha,tatuapé',
# '3 - vermelha,vila matilde',
# '4 - amarela,faria lima',
# '4 - amarela,fradique coutinho',
# '4 - amarela,higienópolis - mackenzie',
# '4 - amarela,luz',
# '4 - amarela,oscar freire',
# '4 - amarela,paulista',
# '4 - amarela,pinheiros',
# '4 - amarela,república',
# '4 - amarela,vila sônia',
# '5 - lilás,aacd - servidor',
# '5 - lilás,adolfo pinheiro',
# '5 - lilás,alto da boa vista',
# '5 - lilás,borba gato',
# '5 - lilás,brooklin',
# '5 - lilás,campo belo',
# '5 - lilás,capão redondo',
# '5 - lilás,eucaliptos',
# '5 - lilás,hospital são paulo',
# '5 - lilás,largo treze',
# '5 - lilás,moema',
# '5 - lilás,santa cruz',
# '5 - lilás,santo amaro',
# '7 - rubi,jundiaí',
# '7 - rubi,palmeiras - barra funda',
# '8 - diamante,amador bueno',
# '8 - diamante,domingos de moraes',
# '8 - diamante,imperatriz leopoldina',
# '8 - diamante,júlio prestes',
# '8 - diamante,lapa',
# '8 - diamante,osasco',
# '8 - diamante,palmeiras - barra funda',
# '8 - diamante,pres. altino',
# '9 - esmeralda,berrini',
# '9 - esmeralda,ceasa',
# '9 - esmeralda,cidade jardim',
# '9 - esmeralda,cidade universitária',
# '9 - esmeralda,granja julieta',
# '9 - esmeralda,hebraica - rebouças',
# '9 - esmeralda,joão dias',
# '9 - esmeralda,mendes - vila natal',
# '9 - esmeralda,morumbi',
# '9 - esmeralda,osasco',
# '9 - esmeralda,pinheiros',
# '9 - esmeralda,pres. altino',
# '9 - esmeralda,santo amaro',
# '9 - esmeralda,vila olímpia',
# '9 - esmeralda,villa - lobos - jaguaré',
